[templates."Xiaomi 18 Pro Max"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M154FF"
device = "madrid"
product = "madrid"
fingerprint = ""
name = "madrid"
marketname = "Xiaomi 18 Pro Max"
author = "GitHub@JokerQi666"