[templates."Xiaomi 18 Pro"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M610BB"
device = "hongkong"
product = "hongkong"
fingerprint = ""
name = "hongkong"
marketname = "Xiaomi 18 Pro"
author = "GitHub@JokerQi666"