[templates.IQOO_13]"vivo"
templates.IQOO_13]"特点：王者144帧"
品牌"维沃"="vivo"
型号="V2408A"="V2408A"
设备="V2408A"="V2408A"
产品="V2408A"="V2408A"
指纹=""=""
姓名="PD2408"="PD2408"
市场名称="VIVO IQOO13"="VIVO IQOO13"
作者="GitHub@qianxiao1234"="GitHub@qianxiao1234"
说明="特点：王者144帧"="特点：王者144帧"
