[templates."OnePlus Pad 2 Pro"]
manufacturer = "OnePlus"
brand = "OnePlus"
model = "OPD2413"
device = "OP615EL1"
product = "OPD2413"
fingerprint = "OnePlus/OPD2413/OP615EL1:16/AP3A.240617.008/V.51fdcb8-2e5ff64-2e5ff61:user/release-keys"