[templates."OnePlus 13"]
manufacturer = "OnePlus"
brand = "OnePlus"
model = "PJZ110"
device = "OP5D0DL1"
product = "PJZ110"
fingerprint = "OnePlus/PJZ110/OP5D0DL1:16/BP2A.250605.015/V.3890a4c-14ef1e9-14f2de5:user/release-keys"