[templates."OnePlus 15"]
manufacturer = "OnePlus"
brand = "OnePlus"
model = "PLK110"
device = "OP60FFL1"
product = "PLK110"
fingerprint = "OnePlus/PLK110/OP60FFL1:16/BP2A.250605.015/B.15d779e_af8764_af8093:user/release-keys"