[templates."OnePlus ACE 6"]
manufacturer = "OnePlus"
brand = "OnePlus"
model = "PLQ110"
device = "OP6113L1"
product = "PLQ110"
fingerprint = "OnePlus/PLQ110/OP6113L1:16/BP2A.250605.015/B.48f7ba8-2511085-251139b:user/release-keys"