[templates."OnePlus ACE 5 Pro"]
manufacturer = "OnePlus"
brand = "OnePlus"
model = "PKR110"
device = "OP60EBL1"
product = "PKR110"
fingerprint = "OnePlus/PKR110/OP60EBL1:16/AP3A.240617.008/V.10eb425_12d9949_12ce9c3:user/release-keys"